SacramentMeetingPlanner/Models/Meeting.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.RegularExpressions;


namespace SacramentMeetingPlanner.Models
{
    public class Meeting
    {
        public int ID { get; set; }

        [Display(Name = "Meeting Date")]
        [Required(ErrorMessage = "Please Enter a Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime MeetingDate { get; set; }

        [Required(ErrorMessage = "Please enter the first and last name of the conductor.")]
        [RegularExpression(@"^([A-Z][a-z]+\s[A-Z][a-z]+)$", ErrorMessage = "First and last name must be capilatized and only contain letters.")]
        public string Conductor { get; set; }
        
        [Display(Name = "Opening Hymn")]
        [Range(1, 341, ErrorMessage = "Please select a Hymn.")]
        public string OpeningHymn { get; set; }

        [Required(ErrorMessage = "Please enter the first and last name of the invocation.")]
        [RegularExpression(@"^([A-Z][a-z]+\s[A-Z][a-z]+)$", ErrorMessage = "First and last name must be capilatized and only contain letters.")]
        public string Invocation { get; set; }
        
        [Display(Name = "Sacrament Hymn")]
        [Range(1, 341, ErrorMessage = "Please select a Hymn.")]
        public string SacramentHymn { get; set; }
        
        [Display(Name = "Closing Hymn")]
        [Range(1, 341, ErrorMessage = "Please select a Hymn.")]
        public string ClosingHymn { get; set; }

        [Required(ErrorMessage = "Please enter the first and last name of the benediction.")]
        [RegularExpression(@"^([A-Z][a-z]+\s[A-Z][a-z]+)$", ErrorMessage = "First and last name must be capilatized and only contain letters.")]
        public string Benediction { get; set; }
        
        public string Notes { get; set; }

        [Display(Name = "Speaking Assignment")]
        public ICollection<SpeakingAssignment> SpeakingAssignments { get; set; }
        
        public ICollection<Speaker> Speakers { get; set; }

        public ICollection<MyModel> MyModels { get; set; }

    }
}

SacramentMeetingPlanner/Models/Meetings.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SacramentMeetingPlanner.Models
{
    public class Meetings
    {
        public int ID { get; set; }
        public DateTime MeetingDate { get; set; }
        public string Conductor { get; set; }
        public string OpeningHymn { get; set; }
        public string Invocation { get; set; }
        public string SacramentHymn { get; set; }
        public ICollection<Speaker> Speakers { get; set; }
        public string ClosingHymn { get; set; }
        public string Benediction { get; set; }
        public string Notes { get; set; }
    }
}

SacramentMeetingPlanner/Controllers/SpeakersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SacramentMeetingPlanner.Data;
using SacramentMeetingPlanner.Models;

namespace SacramentMeetingPlanner.Controllers
{
    public class SpeakersController : Controller
    {
        private readonly MeetingContext _context;

        public SpeakersController(MeetingContext context)
        {
            _context = context;
        }

        // GET: Speakers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Speakers.ToListAsync());
        }

        // GET: Speakers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var speaker = await _context.Speakers
                .Include(s => s.SpeakingAssignments)
                    .ThenInclude(e => e.Meeting)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.ID == id);

            if (speaker == null)
            {
                return NotFound();
            }

            return View(speaker);
        }

        // GET: Speakers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Speakers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name")] Speaker speaker)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(speaker);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (DbUpdateException /* ex */)
            {
                //Log the error (uncomment ex variable name and write a log.
                ModelState.AddModelError("", "Unable to save changes. " +
                    "Try again, and if the problem persists " +
                    "see your system administrator.");
            }
            return View(speaker);
        }

        // GET: Speakers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var speaker = await _context.Speakers.FindAsync(id);
            if (speaker == null)
            {
                return NotFound();
            }
            return View(speaker);
        }

        // POST: Speakers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPost(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var speakerToUpdate = await _context.Speakers.FirstOrDefaultAsync(s => s.ID == id);
            if (await TryUpdateModelAsync<Speaker>(
                speakerToUpdate,
                "",
                s => s.Name))
            {
                try
                {
                    await _context.SaveChangesAsync();
                    //return RedirectToAction(nameof(Index));
                    return RedirectToAction("Index", "Meetings");
                }
                catch (DbUpdateException /* ex */)
                {
                    //Log the error (uncomment ex variable name and write a log.)
                    ModelState.AddModelError("", "Unable to save changes. " +
                        "Try again, and if the problem persists, " +
                        "see your system administrator.");
                }
            }
            return View(speakerToUpdate);
        }

        // GET: Speakers/Delete/5
        public async Task<IActionResult> Delete(int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return NotFound();
            }

            var speaker = await _context.Speakers
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.ID == id);
            if (speaker == null)
            {
                return NotFound();
            }

            if (saveChangesError.GetValueOrDefault())
            {
                ViewData["ErrorMessage"] =
                    "Delete failed. Try again, and if the problem persists " +
                    "see your system administrator.";
            }

            return View(speaker);
        }

        // POST: Speakers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var speaker = await _context.Speakers.FindAsync(id);
            if (speaker == null)
            {
                return RedirectToAction(nameof(Index));
            }

            try
            {
                    _context.Speakers.Remove(speaker);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException /* ex */)
            {
                //Log the error (uncomment ex variable name and write a log.)
                return RedirectToAction(nameof(Delete), new { id = id, saveChangesError = true });
            }
        }

        private bool SpeakerExists(int id)
        {
            return _context.Speakers.Any(e => e.ID == id);
        }
    }
}

SacramentMeetingPlanner/Controllers/SpeakingAssignmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SacramentMeetingPlanner.Data;
using SacramentMeetingPlanner.Models;

namespace SacramentMeetingPlanner.Controllers
{
    public class SpeakingAssignmentsController : Controller
    {
        private readonly MeetingContext _context;

        public SpeakingAssignmentsController(MeetingContext context)
        {
            _context = context;
        }

        // GET: SpeakingAssignments
        public async Task<IActionResult> Index(
             string sortOrder,
             string currentFilter,
             string searchString,
             int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["TopicSortParm"] =
                String.IsNullOrEmpty(sortOrder) ? "Topic_desc" : "";
            ViewData["DateSortParm"] =
                sortOrder == "MeetingDate" ? "MeetingDate_desc" : "MeetingDate";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var meetingContext = _context.SpeakingAssignments.Include(s => s.Meeting).Include(s => s.Speaker);


            if (!String.IsNullOrEmpty(searchString))
            {
                meetingContext = _context.SpeakingAssignments.Where(s => s.Topic.Contains(searchString)).Include(s => s.Meeting).Include(s => s.Speaker);
            }

            if (string.IsNullOrEmpty(sortOrder))
            {
                sortOrder = "Topic";
            }

            bool descending = false;

            if (sortOrder.EndsWith("_desc"))
            {
                sortOrder = sortOrder.Substring(0, sortOrder.Length - 5);
                descending = true;
            }


            if (descending)
            {
                meetingContext = _context.SpeakingAssignments.OrderByDescending(e => e.Topic).Include(s => s.Meeting).Include(s => s.Speaker);
            }
            else
            {
                meetingContext = _context.SpeakingAssignments.OrderBy(e => e.Topic).Include(s => s.Meeting).Include(s => s.Speaker);
            }


            return View(await meetingContext.AsNoTracking().ToListAsync());

        }

        // GET: SpeakingAssignments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var speakingAssignment = await _context.SpeakingAssignments
                .Include(s => s.Meeting)
                .Include(s => s.Speaker)
                .FirstOrDefaultAsync(m => m.SpeakingAssignmentID == id);
            if (speakingAssignment == null)
            {
                return NotFound();
            }

            return View(speakingAssignment);
        }

        // GET: SpeakingAssignments/Create
        public IActionResult Create()
        {
            ViewData["MeetingID"] = new SelectList(_context.Meetings, "ID", "ID");
            ViewData["SpeakerID"] = new SelectList(_context.Speakers, "ID", "ID");
            return View();
        }

        // POST: SpeakingAssignments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SpeakingAssignmentID,MeetingID,SpeakerID,Topic")] SpeakingAssignment speakingAssignment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(speakingAssignment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MeetingID"] = new SelectList(_context.Meetings, "ID", "ID", speakingAssignment.MeetingID);
            ViewData["SpeakerID"] = new SelectList(_context.Speakers, "ID", "ID", speakingAssignment.SpeakerID);
            return View(speakingAssignment);
        }

        // GET: SpeakingAssignments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var speakingAssignment = await _context.SpeakingAssignments.FindAsync(id);
            if (speakingAssignment == null)
            {
                return NotFound();
            }
            ViewData["MeetingID"] = new SelectList(_context.Meetings, "ID", "ID", speakingAssignment.MeetingID);
            ViewData["SpeakerID"] = new SelectList(_context.Speakers, "ID", "ID", speakingAssignment.SpeakerID);
            return View(speakingAssignment);
        }

        // POST: SpeakingAssignments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SpeakingAssignmentID,MeetingID,SpeakerID,Topic")] SpeakingAssignment speakingAssignment)
        {
            if (id != speakingAssignment.SpeakingAssignmentID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(speakingAssignment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SpeakingAssignmentExists(speakingAssignment.SpeakingAssignmentID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                //return RedirectToAction(nameof(Index));
                return RedirectToAction("Index", "Meetings");


            }
            ViewData["MeetingID"] = new SelectList(_context.Meetings, "ID", "ID", speakingAssignment.MeetingID);
            ViewData["SpeakerID"] = new SelectList(_context.Speakers, "ID", "ID", speakingAssignment.SpeakerID);
            return View(speakingAssignment);
        }

        // GET: SpeakingAssignments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var speakingAssignment = await _context.SpeakingAssignments
                .Include(s => s.Meeting)
                .Include(s => s.Speaker)
                .FirstOrDefaultAsync(m => m.SpeakingAssignmentID == id);
            if (speakingAssignment == null)
            {
                return NotFound();
            }

            return View(speakingAssignment);
        }

        // POST: SpeakingAssignments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var speakingAssignment = await _context.SpeakingAssignments.FindAsync(id);
            _context.SpeakingAssignments.Remove(speakingAssignment);
            await _context.SaveChangesAsync();
            //return RedirectToAction(nameof(Index));
            return RedirectToAction("Index", "Meetings");

        }

        private bool SpeakingAssignmentExists(int id)
        {
            return _context.SpeakingAssignments.Any(e => e.SpeakingAssignmentID == id);
        }
    }
}

SacramentMeetingPlanner/Views/Meetings/Create.cshtml
@model SacramentMeetingPlanner.Models.Meeting

@{
    ViewData["Title"] = "Create";
}

<h1 class="heading-font">Whitney Ranch Ward</h1>
<h2>Meeting builder</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MeetingDate" class="control-label">Date</label>
                <input asp-for="MeetingDate" class="form-control" />
                <span asp-validation-for="MeetingDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Conductor" class="control-label"></label>
                <input asp-for="Conductor" class="form-control" />
                <span asp-validation-for="Conductor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OpeningHymn" class="control-label"></label>
                <input asp-for="OpeningHymn" class="form-control" />
                <span asp-validation-for="OpeningHymn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Invocation" class="control-label"></label>
                <input asp-for="Invocation" class="form-control" />
                <span asp-validation-for="Invocation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SacramentHymn" class="control-label"></label>
                <input asp-for="SacramentHymn" class="form-control" />
                <span asp-validation-for="SacramentHymn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClosingHymn" class="control-label"></label>
                <input asp-for="ClosingHymn" class="form-control" />
                <span asp-validation-for="ClosingHymn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Benediction" class="control-label"></label>
                <input asp-for="Benediction" class="form-control" />
                <span asp-validation-for="Benediction" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Notes" class="control-label"></label>
                <input asp-for="Notes" class="form-control" />
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
            <div id="divcontent" class="form-group">
                <button type="button" class="btn btn-sm btn-success" id="addspeaker" onclick="AddTextBox();  this.disabled=true;"><i class="fa fa-angle-right"></i> Add Speaker</button>
            </div>
            <div class="form-group">
                <input type="submit" value="Create Meeting" class="btn btn-primary" />
            </div>
        </form>

    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
<script type="text/javascript">
function GetDynamicTextBox(value) {
    //return ('<hr/><label asp-controller="Speakers" asp-for="Name" class="control-label">Name</label><input asp-for="Name" class="form-control" /><br><label>Topic</label><input asp-for="Topic" class="form-control"/><br><button type="button" class="btn btn-sm btn-danger" onclick="RemoveTextBox(this)"><i class="fa fa-angle-right"></i> Remove Speaker</button>');
    return (  '<hr><label class="control-label">Name</label><input name="Name" id="Name"class="form-control" required><br><label class="control-label">Topic</label><input name="Topic" id="Topic" class="form-control" required><br><button type="button" class="btn btn-sm btn-danger" onclick="RemoveTextBox(this); document.getElementById(\'addspeaker\').disabled=false;"><i class="fa fa-angle-right"></i> Remove Speaker</button>');
}
function AddTextBox() {
    var div = document.createElement('DIV');
    div.innerHTML = GetDynamicTextBox("");
    document.getElementById("divcontent").appendChild(div);
}
function RemoveTextBox(div) {
    document.getElementById("divcontent").removeChild(div.parentNode);
}
</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SacramentMeetingPlanner/Views/Meetings/Delete.cshtml
@model SacramentMeetingPlanner.Models.Meeting

@{
    ViewData["Title"] = "Delete";
}

<h1 class="heading-font">Whitney Ranch Ward</h1>

<h3>Are you sure you want to delete this meeting?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MeetingDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MeetingDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Conductor)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Conductor)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.OpeningHymn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.OpeningHymn)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Invocation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Invocation)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SacramentHymn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SacramentHymn)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ClosingHymn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ClosingHymn)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Benediction)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Benediction)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Notes)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SpeakingAssignments)
        </dt>
        <dd class="col-sm-10">
            <table class="table">
                <tr>
                    <th>Name</th>
                    <th>Topic</th>
                </tr>
                @foreach (var item in Model.SpeakingAssignments)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Speaker.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Topic)
                        </td>
                    </tr>
                }
            </table>
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SacramentMeetingPlanner/Views/Meetings/Edit.cshtml
@model SacramentMeetingPlanner.Models.Meeting

@{
    ViewData["Title"] = "Edit";
}

<h1 class="heading-font">Whitney Ranch Ward</h1>
<h2>Edit Meeting</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="MeetingDate" class="control-label">Date</label>
                <input asp-for="MeetingDate" class="form-control" />
                <span asp-validation-for="MeetingDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Conductor" class="control-label"></label>
                <input asp-for="Conductor" class="form-control" />
                <span asp-validation-for="Conductor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OpeningHymn" class="control-label"></label>
                <input asp-for="OpeningHymn" class="form-control" />
                <span asp-validation-for="OpeningHymn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Invocation" class="control-label"></label>
                <input asp-for="Invocation" class="form-control" />
                <span asp-validation-for="Invocation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SacramentHymn" class="control-label"></label>
                <input asp-for="SacramentHymn" class="form-control" />
                <span asp-validation-for="SacramentHymn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClosingHymn" class="control-label"></label>
                <input asp-for="ClosingHymn" class="form-control" />
                <span asp-validation-for="ClosingHymn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Benediction" class="control-label"></label>
                <input asp-for="Benediction" class="form-control" />
                <span asp-validation-for="Benediction" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Notes" class="control-label"></label>
                <input asp-for="Notes" class="form-control" />
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <table class="table">
                    <tr>
                        <th>Name</th>
                        <th>Topic</th>
                        <th></th>
                    </tr>
                    @foreach (var item in Model.SpeakingAssignments)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Speaker.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Topic)
                            </td>
                            <td>
                                <a asp-controller="Speakers" asp-action="Edit" asp-route-id="@item.SpeakerID">Edit Name</a> |
                                <a asp-controller="SpeakingAssignments" asp-action="Edit" asp-route-id="@item.SpeakingAssignmentID">Edit Topic</a> |
                                <a asp-controller="SpeakingAssignments" asp-action="Delete" asp-route-id="@item.SpeakingAssignmentID">Delete</a>
                            </td>
                        </tr>
                    }
                </table>
            </div>
            <div id="divcontent" class="form-group">
                <button type="button" id="addspeaker" class="btn btn-sm btn-success" onclick="AddTextBox();  this.disabled=true;"><i class="fa fa-angle-right"></i> Add Speaker</button>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
<script type="text/javascript">
    function GetDynamicTextBox(value) {
        //return ('<hr/><label asp-controller="Speakers" asp-for="Name" class="control-label">Name</label><input asp-for="Name" class="form-control" /><br><label>Topic</label><input asp-for="Topic" class="form-control"/><br><button type="button" class="btn btn-sm btn-danger" onclick="RemoveTextBox(this)"><i class="fa fa-angle-right"></i> Remove Speaker</button>');
        return ('<hr><label class="control-label">Name</label><input name="Name" id="Name"class="form-control" required><br><label class="control-label">Topic</label><input name="Topic" id="Topic" class="form-control" required><br><button type="button" class="btn btn-sm btn-danger" onclick="RemoveTextBox(this); document.getElementById(\'addspeaker\').disabled=false;"><i class="fa fa-angle-right"></i> Cancel</button>');
    }
    function AddTextBox() {
        var div = document.createElement('DIV');
        div.innerHTML = GetDynamicTextBox("");
        document.getElementById("divcontent").appendChild(div);
    }
    function RemoveTextBox(div) {
        document.getElementById("divcontent").removeChild(div.parentNode);
    }
</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SacramentMeetingPlanner/Views/Meetings/Index.cshtml
@model IEnumerable<SacramentMeetingPlanner.Models.Meeting>

@{
    ViewData["Title"] = "Index";
}

<h1 class="heading-font">Whitney Ranch Ward</h1>

<p>
    <a class="create-font" asp-action="Create">Build meeting</a>
</p>
<table class="table table-shadow">
    <thead class="header-color">
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["DateSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Meeting Date</a>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Conductor)
            </th>
            <th>
                Number of Speakers
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Notes)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MeetingDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Conductor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SpeakingAssignments.Count)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Notes)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Make changes</a> |
                <a asp-action="Details" asp-route-id="@item.ID">View/Print</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Remove</a>
            </td>
        </tr>
}
    </tbody>
</table>